name: Destroy
on: 
  workflow_dispatch:
  schedule: 
    - cron:  '0 8 * * *'
jobs:
  destroy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ethanbayliss/docker-aws-cdk:latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm install
    - name: cdk destroy
      run: cdk destroy --all --force
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-southeast-2