# name: GitHub Actions on change
# on: [push]
# jobs:
#   Explore-GitHub-Actions:
#     runs-on: ubuntu-latest
#     steps:
#       - run: npm install --global --production
#       - run: npm run build
#       #- run: cdk diff
#       #- run: cdk doctor
#       #approval?
#       - run: cdk deploy --progress=events --all 
# runs:
#   using: 'docker'
#   image: ./docker-aws-cdk/Dockerfile'


on: workflow_call

name: 'Deploy CDK'
description: 'Deploy a CDK project automatically'
inputs:
  ALPINE_VERSION:  # id of input
    description: 'Alpine Linux Version'
    required: true
    default: 3.14
runs:
  using: 'docker'
  image: './docker-aws-cdk/Dockerfile'
  args:
    - ${{ inputs.ALPINE_VERSION }}