on: push
jobs:
  compile:
    runs-on: ubuntu-latest
    container: ghcr.io/ethanbayliss/docker-aws-cdk:latest
    steps: 
      - run: |
          echo test
          echo test123

name: Build and deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ethanbayliss/docker-aws-cdk:latest
    steps:
    - uses: actions/checkout@v2
    - run: cdk deploy --require-approval never --progress events
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        WEBHOSTING_BUCKET_NAME: my-awesome-bucket